### ISSUE TITLE
Is it possible to port the code to Xilinx Versal Architecture

### ISSUE THREAD

**Issue by Oxygen-Chu** [capitanov/fp23fftk#1]
As we know, Xilinx Versal architecture has hardened FP32 primitive, which will save power and increase performance.
I wonder is it possible to port your fp23fftk to Versal, and use single-precision floating-point format as input/out?

**Comment by hukenovs** [comment]
Hello!

You cannot port fp23 format directly to Versal, but if you change the basic math blocks (adder, multiplier, butterflies) with FP32 blocks - it will work correctly.

BR,
Alexander
